### ISSUE TITLE
is this your AL account too?

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/social#11]
tried to add you to our Groceristar team and use your email, but not sure if this is your main account
https://angel.co/mahimavmishra

**Comment by atherdon** [comment]
maybe you can share with me your other email, related to your main AL account - so i can add that profile to our team members page

**Comment by mahimamishra** [comment]
My associated mail with angellist account is 1285Singh@gmail.com

**Comment by atherdon** [comment]
gotcha. maybe this was your previous account. will replace old with new
account


On 07-Jun-2018 at 02:11 AM, Mahima Mishra wrote:


My associated mail with angellist account is 1285Singh@gmail.com

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/social/issues/11#issuecomment-395270243>,
or mute the thread

**Comment by atherdon** [comment]
just added your acc to AL
